# Generated by Django 4.0.5 on 2022-08-06 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogcrud', '0002_blogpost_title_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogPost',
            new_name='Post',
        ),
    ]
