# Generated by Django 4.0.5 on 2022-08-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcrud', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
