# Generated by Django 4.0.5 on 2022-08-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogcrud', '0008_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
